In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df = pd.read_csv("../data/train.csv")
rows_with_nan = train_df[train_df.isna().any(axis=1)]
conditions = list(rows_with_nan.columns)
conditions = conditions[1:]
print("Count of NaN values :")
for cond in conditions:
    x = rows_with_nan[cond].isna()
    print("Number of NaN values for condition ", cond, " : ", sum(x))

Count of NaN values :
Number of NaN values for condition  spinal_canal_stenosis_l1_l2  :  1
Number of NaN values for condition  spinal_canal_stenosis_l2_l3  :  1
Number of NaN values for condition  spinal_canal_stenosis_l3_l4  :  1
Number of NaN values for condition  spinal_canal_stenosis_l4_l5  :  1
Number of NaN values for condition  spinal_canal_stenosis_l5_s1  :  1
Number of NaN values for condition  left_neural_foraminal_narrowing_l1_l2  :  2
Number of NaN values for condition  left_neural_foraminal_narrowing_l2_l3  :  2
Number of NaN values for condition  left_neural_foraminal_narrowing_l3_l4  :  2
Number of NaN values for condition  left_neural_foraminal_narrowing_l4_l5  :  2
Number of NaN values for condition  left_neural_foraminal_narrowing_l5_s1  :  2
Number of NaN values for condition  right_neural_foraminal_narrowing_l1_l2  :  8
Number of NaN values for condition  right_neural_foraminal_narrowing_l2_l3  :  8
Number of NaN values for condition  right_neural_foraminal_narrowing_l3_l4  :  8
Number of NaN values for condition  right_neural_foraminal_narrowing_l4_l5  :  8
Number of NaN values for condition  right_neural_foraminal_narrowing_l5_s1  :  8
Number of NaN values for condition  left_subarticular_stenosis_l1_l2  :  164
Number of NaN values for condition  left_subarticular_stenosis_l2_l3  :  82
Number of NaN values for condition  left_subarticular_stenosis_l3_l4  :  3
Number of NaN values for condition  left_subarticular_stenosis_l4_l5  :  3
Number of NaN values for condition  left_subarticular_stenosis_l5_s1  :  11
Number of NaN values for condition  right_subarticular_stenosis_l1_l2  :  161
Number of NaN values for condition  right_subarticular_stenosis_l2_l3  :  82
Number of NaN values for condition  right_subarticular_stenosis_l3_l4  :  2
Number of NaN values for condition  right_subarticular_stenosis_l4_l5  :  2
Number of NaN values for condition  right_subarticular_stenosis_l5_s1  :  7

In [3]:
study_ids = train_df["study_id"].values

In [5]:
print("Count of NaN values :")
print()
subjects_with_nans = []
nans_per_cond = np.zeros(5)
for i, cond in enumerate(conditions):
    x = rows_with_nan[cond].isna().values
    subjects_with_nans += list(study_ids[np.where(x==True)[0]])
    
    print(cond, " : ", sum(x))

Count of NaN values :

spinal_canal_stenosis_l1_l2  :  1
spinal_canal_stenosis_l2_l3  :  1
spinal_canal_stenosis_l3_l4  :  1
spinal_canal_stenosis_l4_l5  :  1
spinal_canal_stenosis_l5_s1  :  1
left_neural_foraminal_narrowing_l1_l2  :  2

IndexError: index 5 is out of bounds for axis 0 with size 5

In [10]:
train_df

,study_id,spinal_canal_stenosis_l1_l2,spinal_canal_stenosis_l2_l3,spinal_canal_stenosis_l3_l4,spinal_canal_stenosis_l4_l5,spinal_canal_stenosis_l5_s1,left_neural_foraminal_narrowing_l1_l2,left_neural_foraminal_narrowing_l2_l3,left_neural_foraminal_narrowing_l3_l4,left_neural_foraminal_narrowing_l4_l5,...,left_subarticular_stenosis_l1_l2,left_subarticular_stenosis_l2_l3,left_subarticular_stenosis_l3_l4,left_subarticular_stenosis_l4_l5,left_subarticular_stenosis_l5_s1,right_subarticular_stenosis_l1_l2,right_subarticular_stenosis_l2_l3,right_subarticular_stenosis_l3_l4,right_subarticular_stenosis_l4_l5,right_subarticular_stenosis_l5_s1
0,4003253,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild
1,4646740,Normal/Mild,Normal/Mild,Moderate,Severe,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Normal/Mild,Normal/Mild,Severe,Normal/Mild,Normal/Mild,Moderate,Moderate,Moderate,Normal/Mild
2,7143189,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild
3,8785691,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild
4,10728036,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Normal/Mild
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1970,4282019580,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Moderate,Moderate
1971,4283570761,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild
1972,4284048608,Normal/Mild,Normal/Mild,Normal/Mild,Severe,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Severe,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Severe,Normal/Mild
1973,4287160193,Normal/Mild,Moderate,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,...,Normal/Mild,Severe,Moderate,Moderate,Normal/Mild,Normal/Mild,Normal/Mild,Moderate,Moderate,Normal/Mild
1974,4290709089,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,...,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild,Normal/Mild

In [12]:
train_df = pd.read_csv("../data/train.csv")
train_df = train_df.dropna()
text2int = {"Normal/Mild": 0, "Moderate": 1, "Severe":2}
train_df = train_df.replace(text2int)


# train_df = train_df[["study_id",
#                     "left_neural_foraminal_narrowing_l1_l2",
#                     "left_neural_foraminal_narrowing_l2_l3",
#                     "left_neural_foraminal_narrowing_l3_l4",
#                     "left_neural_foraminal_narrowing_l4_l5",
#                     "left_neural_foraminal_narrowing_l5_s1",
#                     "right_neural_foraminal_narrowing_l1_l2",
#                     "right_neural_foraminal_narrowing_l2_l3",
#                     "right_neural_foraminal_narrowing_l3_l4",
#                     "right_neural_foraminal_narrowing_l4_l5",
#                     "right_neural_foraminal_narrowing_l5_s1"]]

df = pd.DataFrame(train_df[["left_neural_foraminal_narrowing_l1_l2",
                            "left_neural_foraminal_narrowing_l2_l3",
                            "left_neural_foraminal_narrowing_l3_l4",
                            "left_neural_foraminal_narrowing_l4_l5",
                            "left_neural_foraminal_narrowing_l5_s1",
                            "right_neural_foraminal_narrowing_l1_l2",
                            "right_neural_foraminal_narrowing_l2_l3",
                            "right_neural_foraminal_narrowing_l3_l4",
                            "right_neural_foraminal_narrowing_l4_l5",
                            "right_neural_foraminal_narrowing_l5_s1"]].sum(axis=1))

df.rename(columns={0: "count"}, inplace=True)
idx = np.where(df.values[:, 0]<=5)
exclude = np.random.choice(idx[0], size=500, replace=False)
exclude = list(train_df.iloc[exclude]["study_id"].values)

In [17]:
train_sub = train_df.filter(regex="_subarticular_|study_id")

In [19]:
rows_with_2 = train_sub[train_sub.isin([2]).any(axis=1)]

In [20]:
rows_with_2

,study_id,left_subarticular_stenosis_l1_l2,left_subarticular_stenosis_l2_l3,left_subarticular_stenosis_l3_l4,left_subarticular_stenosis_l4_l5,left_subarticular_stenosis_l5_s1,right_subarticular_stenosis_l1_l2,right_subarticular_stenosis_l2_l3,right_subarticular_stenosis_l3_l4,right_subarticular_stenosis_l4_l5,right_subarticular_stenosis_l5_s1
1,4646740,0,0,0,2,0,0,1,1,1,0
8,22191399,0,0,0,1,1,0,0,0,2,1
10,29931867,0,0,1,1,1,1,2,2,1,2
12,38281420,0,0,0,0,0,0,1,1,2,2
13,40745534,0,0,1,2,1,0,0,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...
1967,4279833491,0,0,0,2,0,0,0,0,2,0
1968,4279881930,0,2,2,2,0,1,1,2,2,0
1969,4279958262,0,2,2,1,2,0,2,2,2,1
1972,4284048608,0,0,0,2,0,0,0,0,2,0
1973,4287160193,0,2,1,1,0,0,0,1,1,0